// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdToznzxP-9mmUjDUvpJM07Jjy6_EQ-H4',
    appId: '1:449654256607:web:e669b6938e8a9441630a6a',
    messagingSenderId: '449654256607',
    projectId: 'connect-care-22',
    authDomain: 'connect-care-22.firebaseapp.com',
    storageBucket: 'connect-care-22.firebasestorage.app',
    measurementId: 'G-12K1ZRVT17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9oChnzpg3lTJTjwqgivLGKPyejcrYhfU',
    appId: '1:449654256607:android:376b86a49873b9a4630a6a',
    messagingSenderId: '449654256607',
    projectId: 'connect-care-22',
    storageBucket: 'connect-care-22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx7GuAsp7P88ihCxzXS4B5ePsbuRxTPhM',
    appId: '1:449654256607:ios:0fc7cd2fd96d3566630a6a',
    messagingSenderId: '449654256607',
    projectId: 'connect-care-22',
    storageBucket: 'connect-care-22.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx7GuAsp7P88ihCxzXS4B5ePsbuRxTPhM',
    appId: '1:449654256607:ios:0fc7cd2fd96d3566630a6a',
    messagingSenderId: '449654256607',
    projectId: 'connect-care-22',
    storageBucket: 'connect-care-22.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdToznzxP-9mmUjDUvpJM07Jjy6_EQ-H4',
    appId: '1:449654256607:web:ffcc7be75e2fc801630a6a',
    messagingSenderId: '449654256607',
    projectId: 'connect-care-22',
    authDomain: 'connect-care-22.firebaseapp.com',
    storageBucket: 'connect-care-22.firebasestorage.app',
    measurementId: 'G-7WT5QYG0C0',
  );
}
